/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.reservation.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliar
 */
public class BookingMainPage extends javax.swing.JFrame {

    /**
     * Creates new form BookingMainPage
     */
    private final Connection connection = AirlineReservationSystem.connection;
    ResultSet rs = null;
    PreparedStatement pst = null;
    Statement st = AirlineReservationSystem.statement;
     boolean testActionListenerActive = false;
    
    public BookingMainPage() {
        initComponents();
        getFlightsIds();
        displayBookingDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pNameField = new javax.swing.JTextField();
        genderField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pNumField1 = new javax.swing.JTextField();
        nationalityField1 = new javax.swing.JTextField();
        passIDField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        fIdCMBox1 = new javax.swing.JComboBox<>();
        statusCMBox = new javax.swing.JComboBox<>();
        cancelBtn = new javax.swing.JButton();
        amount = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(123, 50, 250));

        jLabel1.setBackground(new java.awt.Color(123, 50, 250));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOKINGS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        bookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket ID", "PName", "Flight ID", "PGender", "PNumber", "PNationality", "Amount Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        bookingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bookingTable);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Passenger ID");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Passenger Name");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Flight ID");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Gender");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Passport Number");

        bookBtn.setBackground(new java.awt.Color(123, 50, 250));
        bookBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookBtn.setText("BOOK");
        bookBtn.setFocusPainted(false);
        bookBtn.setFocusable(false);
        bookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookBtnMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(123, 50, 250));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RESET");
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Amount Status");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Nationality");

        pNameField.setEditable(false);
        pNameField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        genderField.setEditable(false);
        genderField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        jButton3.setBackground(new java.awt.Color(123, 50, 250));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BACK");
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        pNumField1.setEditable(false);
        pNumField1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        nationalityField1.setEditable(false);
        nationalityField1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        nationalityField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalityField1ActionPerformed(evt);
            }
        });

        passIDField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/reservation/system/icons/search.png"))); // NOI18N
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        fIdCMBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        fIdCMBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fIdCMBox1MouseClicked(evt);
            }
        });
        fIdCMBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fIdCMBox1ActionPerformed(evt);
            }
        });

        statusCMBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unpaid", "Paid" }));

        cancelBtn.setBackground(new java.awt.Color(123, 50, 250));
        cancelBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("CANCEL");
        cancelBtn.setFocusPainted(false);
        cancelBtn.setFocusable(false);
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        amount.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        amount.setText("Amount");

        amountField.setEditable(false);
        amountField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        amountField.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(passIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(amount)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel7))
                                                .addGap(6, 6, 6))
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(fIdCMBox1, 0, 156, Short.MAX_VALUE)
                                                    .addComponent(pNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(genderField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(pNumField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(nationalityField1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                                    .addComponent(statusCMBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(amountField)))))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(bookBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(fIdCMBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(genderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(pNumField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(nationalityField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(amount))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusCMBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bookBtn)
                            .addComponent(cancelBtn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        dispose();
        new MainPage().setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void nationalityField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalityField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nationalityField1ActionPerformed

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        // TODO add your handling code here:
        getPassengerData();
    }//GEN-LAST:event_searchBtnMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jButton2MouseClicked

    private void fIdCMBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fIdCMBox1ActionPerformed
        // TODO add your handling code here:
        if(testActionListenerActive){
            try {
               String query = "SELECT * FROM Flights WHERE FlightId ="+fIdCMBox1.getSelectedItem();
               System.out.println(query);
               rs = st.executeQuery(query);
               amountField.setText(rs.getString("price"));
             
           } catch (SQLException ex) {
               Logger.getLogger(BookingMainPage.class.getName()).log(Level.SEVERE, null, ex);
           } 
        }
    }//GEN-LAST:event_fIdCMBox1ActionPerformed

   
    private void fIdCMBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fIdCMBox1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fIdCMBox1MouseClicked

    private void bookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseClicked
        // TODO add your handling code here:
        if(passIDField.getText().isEmpty() || pNameField.getText().isEmpty() || fIdCMBox1.getSelectedIndex() == -1 || 
                genderField.getText().isEmpty() || nationalityField1.getText().isEmpty() || pNumField1.getText().isEmpty() || amountField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all the information.");
        }
        else if(statusCMBox.getSelectedItem() != "Paid"){
            JOptionPane.showMessageDialog(null, "Please update the status to Paid.");
        }
        else{
            try {
                String checkSeats = "SELECT Seats FROM Flights WHERE flightId =" + fIdCMBox1.getSelectedItem();
                pst = connection.prepareStatement(checkSeats);
                rs = pst.executeQuery();
                int seats = Integer.parseInt(rs.getString("Seats"));
                if(seats > 0){
                    String reserveSeat = "UPDATE Flights SET Seats = Seats - 1 WHERE flightId =" + fIdCMBox1.getSelectedItem();
                    System.out.println(reserveSeat);
                    pst = connection.prepareStatement(reserveSeat);
                    pst.executeUpdate();
                    String updateQuery = "UPDATE Passengers SET status="+ '"' +"Paid"+ '"' + ", amountPaid = " + amountField.getText() + ", flightId =" + '"' + fIdCMBox1.getSelectedItem() + '"'  + " WHERE passID = "+ '"' +passIDField.getText()+ '"';
                    System.out.println(updateQuery);
                    pst = connection.prepareStatement(updateQuery);
                    pst.executeUpdate();
                    displayBookingDetails();
                    clearFields();
                    JOptionPane.showMessageDialog(null, "Booking successfully completed.");         
                }
                else{
                    JOptionPane.showMessageDialog(null, "Sorry, No seats available.");    
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bookBtnMouseClicked

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        // TODO add your handling code here:
        try{
            String cancelQuery = "UPDATE Passengers SET status = "+'"'+"Unpaid"+'"'+", flightId = NULL, amountPaid = NULL WHERE passID ="+'"'+passIDField.getText()+'"';
            System.out.println(cancelQuery);
            pst = connection.prepareStatement(cancelQuery);
            pst.executeUpdate();
            String unreversveSeat = "UPDATE Flights SET Seats = Seats + 1 WHERE flightId =" + fIdCMBox1.getSelectedItem();
            System.out.println(unreversveSeat);
            pst = connection.prepareStatement(unreversveSeat);
            pst.executeUpdate();
            displayBookingDetails();
            clearFields();
            JOptionPane.showMessageDialog(null, "Flight booking is cancelled sussussfully..");   
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void bookingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
        int tableIndex = bookingTable.getSelectedRow();
        passIDField.setText(model.getValueAt(tableIndex, 0).toString());
        pNameField.setText(model.getValueAt(tableIndex, 1).toString());
        fIdCMBox1.setSelectedItem(model.getValueAt(tableIndex, 2).toString());
        genderField.setText(model.getValueAt(tableIndex, 3).toString());
        pNumField1.setText(model.getValueAt(tableIndex, 4).toString());
        nationalityField1.setText(model.getValueAt(tableIndex, 5).toString());
        statusCMBox.setSelectedItem(model.getValueAt(tableIndex, 6).toString());
    }//GEN-LAST:event_bookingTableMouseClicked
 
    
    private void displayBookingDetails(){
         try{
            DefaultTableModel model = (DefaultTableModel) bookingTable.getModel();
            model.setRowCount(0);
            if(connection != null){
                String query = "SELECT * FROM Passengers WHERE status = "+ '"' + "Paid" + '"';
                pst = connection.prepareStatement(query);
                rs = pst.executeQuery();
              
                Object[] data = new Object[7];
                while(rs.next()){
                    data[0] = rs.getString("passID");
                    data[1] = rs.getString("pName");
                    data[2] = rs.getString("flightId");
                    data[3] = rs.getString("Gender");
                    data[4] = rs.getString("passNum");
                    data[5] = rs.getString("nationality");
                    data[6] = rs.getString("status");
                    model.addRow(data);
                }
            }
        }
        catch(Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    private void clearFields(){
        passIDField.setText("");
        pNameField.setText("");
        genderField.setText("");
        pNumField1.setText("");
        nationalityField1.setText("");
        statusCMBox.setSelectedIndex(0);
    }
    
    private void getFlightsIds(){
        try {
            st = connection.createStatement();
            String query = "SELECT * FROM Flights";
            rs = st.executeQuery(query);
            while(rs.next()){
                String fID = rs.getString("FlightId");
                testActionListenerActive = false;
                fIdCMBox1.addItem(fID);
            }
            testActionListenerActive = true;
        } catch (SQLException ex) {
            Logger.getLogger(BookingMainPage.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    
    private void getPassengerData(){
        String query = "SELECT * FROM Passengers WHERE passID =" + '"' + passIDField.getText()+ '"' + ";";
       
        try {
            st = connection.createStatement();
            
            rs = st.executeQuery(query);
            if(rs.next()){
                pNameField.setText(rs.getString("pName"));
                genderField.setText(rs.getString("Gender"));
                pNumField1.setText(rs.getString("passNum"));
                nationalityField1.setText(rs.getString("nationality"));
                statusCMBox.setSelectedItem(rs.getString("status"));
            }
            else{
                clearFields();
                JOptionPane.showMessageDialog(this, "No record found.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BookingMainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton bookBtn;
    private javax.swing.JTable bookingTable;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> fIdCMBox1;
    private javax.swing.JTextField genderField;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nationalityField1;
    private javax.swing.JTextField pNameField;
    private javax.swing.JTextField pNumField1;
    private javax.swing.JTextField passIDField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> statusCMBox;
    // End of variables declaration//GEN-END:variables
}
